export const dabsData = {
  1: [
    {
      id: "11",
      site: "Rue",
      nature: "Sinistre",
      part_end: "abc",
      pour_end: 0.2,
      type_ret: "abc",
      adm: 22,
      pour_adm: 0.8,
      tot_rec: 1260,
    },
    {
      id: "12",
      site: "Bridge",
      nature: "Sinistre",
      part_end: "abc",
      pour_end: 1,
      type_ret: "abc",
      adm: 30,
      pour_adm: 1,
      tot_rec: 44890,
    },
  ],
  2: [
    {
      id: "21",
      site: "Rue",
      nature: "Sinistre",
      part_end: "abc",
      pour_end: 0.2,
      type_ret: "abc",
      adm: 22,
      pour_adm: 0.8,
      tot_rec: 1260,
    },
    {
      id: "22",
      site: "Bridge",
      nature: "Sinistre",
      part_end: "abc",
      pour_end: 1,
      type_ret: "abc",
      adm: 30,
      pour_adm: 1,
      tot_rec: 44890,
    },
  ],
  3: [],
  4: [],
  5: [],
  6: [],
  7: [],
  8: [],
  9: [],
  10: [],
};
