export const facturesDABData = {
  1: [
    {
      id: "11",
      desc_fact: "Facture 1",
      date_fact: "2021-01-11",
      site_con: "Casablanca",
      montant_rec: 2460,
      tax: false,
    },
    {
      id: "12",
      desc_fact: "Facture 2",
      date_fact: "2021-09-30",
      site_con: "Rabat",
      montant_rec: 1220,
      tax: true,
    },
  ],
  2: [
    {
      id: "21",
      desc_fact: "Facture 1",
      date_fact: "2021-01-11",
      site_con: "Casablanca",
      montant_rec: 123456,
      tax: false,
    },
    {
      id: "22",
      desc_fact: "Facture 2",
      date_fact: "2021-09-30",
      site_con: "Rabat",
      montant_rec: 99999,
      tax: true,
    },
  ],
  3: [],
  4: [],
  5: [],
  6: [],
  7: [],
  8: [],
  9: [],
  10: [],
};

export const facturesMPTData = {
  1: [
    {
      id: "11",
      desc_fact: "Factureeeeeeee 1",
      date_fact: "2021-01-11",
      site_con: "Casablanca",
      montant_rec: 10547,
      tax: false,
    },
    {
      id: "12",
      desc_fact: "Facture 2",
      date_fact: "2021-09-30",
      site_con: "Rabat",
      montant_rec: 8963.36,
      tax: true,
    },
  ],
  2: [
    {
      id: "21",
      desc_fact: "Facture 1",
      date_fact: "2021-01-11",
      site_con: "Casablanca",
      montant_rec: 3469.2,
      tax: false,
    },
    {
      id: "22",
      desc_fact: "Facture 2",
      date_fact: "2021-09-30",
      site_con: "Rabat",
      montant_rec: 1244,
      tax: true,
    },
  ],
  3: [],
  4: [],
  5: [],
  6: [],
  7: [],
  8: [],
  9: [],
  10: [],
};

export const facturesMIData = {
  1: [
    {
      id: "11",
      desc_fact: "Facture MI 1",
      date_fact: "2021-01-11",
      site_con: "Casablanca",
      montant_rec: 3655.54,
      tax: false,
    },
    {
      id: "12",
      desc_fact: "Facture MI 2",
      date_fact: "2021-09-30",
      site_con: "Rabat",
      montant_rec: 2978.3,
      tax: true,
    },
  ],
  2: [
    {
      id: "21",
      desc_fact: "Facture MI 1",
      date_fact: "2021-01-11",
      site_con: "Casablanca",
      montant_rec: 123456,
      tax: false,
    },
    {
      id: "22",
      desc_fact: "Facture MI 2",
      date_fact: "2021-09-30",
      site_con: "Rabat",
      montant_rec: 99999,
      tax: true,
    },
  ],
  3: [],
  4: [],
  5: [],
  6: [],
  7: [],
  8: [],
  9: [],
  10: [],
};
