export const machineriesDABData = {
  1: [
    {
      code: "Caterpillar",
      desc: "Big machine",
      maintenance: 10,
      site_conc: "Madrid",
      hrs_fonc: 12,
      hrs_stat: 20,
      cout: 0,
      taux_fonc: 12,
    },
    {
      code: "Caterpillar 2",
      desc: "Big machine 2",
      maintenance: 15,
      site_conc: "Madrid",
      hrs_fonc: 12,
      hrs_stat: 20,
      cout: 0,
      taux_fonc: 12,
    },
  ],
  2: [
    {
      code: "Hitachi",
      desc: "Big machine",
      maintenance: 2,
      site_conc: "Madrid",
      hrs_fonc: 12,
      hrs_stat: 20,
      cout: 0,
      taux_fonc: 12,
    },
    {
      code: "Hitachi 2",
      desc: "Big machine 2",
      maintenance: 0,
      site_conc: "Madrid",
      hrs_fonc: 12,
      hrs_stat: 20,
      cout: 0,
      taux_fonc: 12,
    },
  ],
  3: [],
  4: [],
  5: [],
  6: [],
  7: [],
  8: [],
  9: [],
  10: [],
};

export const machineriesMPTData = {
  1: [
    {
      code: "Honda",
      desc: "Big machine",
      maintenance: 11,
      site_conc: "Madrid",
      hrs_fonc: 12,
      hrs_stat: 20,
      cout: 0,
      taux_fonc: 12,
    },
    {
      code: "Honda 2",
      desc: "Big machine 2",
      maintenance: 24,
      site_conc: "Madrid",
      hrs_fonc: 12,
      hrs_stat: 20,
      cout: 0,
      taux_fonc: 12,
    },
    {
      code: "Mercedes 3",
      desc: "Big machine",
      maintenance: 3,
      site_conc: "Madrid",
      hrs_fonc: 12,
      hrs_stat: 20,
      cout: 0,
      taux_fonc: 12,
    },
  ],
  2: [
    {
      code: "BobCat",
      desc: "Big machine",
      maintenance: 12,
      site_conc: "Madrid",
      hrs_fonc: 12,
      hrs_stat: 20,
      cout: 0,
      taux_fonc: 12,
    },
    {
      code: "Actros",
      desc: "Big machine 2",
      maintenance: 5,
      site_conc: "Madrid",
      hrs_fonc: 12,
      hrs_stat: 20,
      cout: 0,
      taux_fonc: 12,
    },
  ],
  3: [],
  4: [],
  5: [],
  6: [],
  7: [],
  8: [],
  9: [],
  10: [],
};

export const machineriesMIData = {
  1: [
    {
      code: "Hyandai",
      desc: "Big machine",
      maintenance: 10,
      site_conc: "Madrid",
      hrs_fonc: 12,
      hrs_stat: 20,
      cout: 0,
      taux_fonc: 12,
    },
    {
      code: "Lamborghini",
      desc: "Big machine 2",
      maintenance: 0,
      site_conc: "Madrid",
      hrs_fonc: 12,
      hrs_stat: 20,
      cout: 0,
      taux_fonc: 12,
    },
  ],
  2: [
    {
      code: "Bulldozer",
      desc: "Big machine",
      maintenance: 1,
      site_conc: "Madrid",
      hrs_fonc: 12,
      hrs_stat: 20,
      cout: 0,
      taux_fonc: 12,
    },
    {
      code: "Front Loader",
      desc: "Big machine 2",
      maintenance: 0,
      site_conc: "Madrid",
      hrs_fonc: 12,
      hrs_stat: 20,
      cout: 0,
      taux_fonc: 12,
    },
  ],
  3: [],
  4: [],
  5: [],
  6: [],
  7: [],
  8: [],
  9: [],
  10: [],
};
